services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: shorty-db
    environment:
      POSTGRES_USER: shorty
      POSTGRES_PASSWORD: shorty
      POSTGRES_DB: shorty
      PGDATA: /tmp/pgdata
    ports:
      - "5432:5432"
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=1g
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pg_cron"
      - "-c"
      - "cron.database_name=shorty"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shorty"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-test:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: shorty-db-test
    environment:
      POSTGRES_USER: shorty
      POSTGRES_PASSWORD: shorty
      POSTGRES_DB: shorty
      PGDATA: /tmp/pgdata
    ports:
      - "5433:5432"
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=1g
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pg_cron"
      - "-c"
      - "cron.database_name=shorty"
      - "-c"
      - "app.allow_nuke=true"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shorty"]
      interval: 10s
      timeout: 5s
      retries: 5
